"""
Warehouse RL — LLM Inference Loop
===================================
Connects an LLM (via the Hugging Face Router API) to the Warehouse RL
environment so it can reason and act across multiple turns.

The LLM receives a structured prompt containing:
  • Current observation (position, battery, inventory, visible cells)
  • Product manifest (priority, location, status)
  • A reasoning hint generated by the environment
  • The full action history of the current episode

The LLM must output a valid JSON action each turn.

Usage
-----
  # 1. Start the environment server first:
  #    uvicorn src.envs.warehouse_env.server.app:app --port 8000

  # 2. Set your Hugging Face token:
  #    export HF_TOKEN=hf_...

  # 3. Run the inference loop:
  #    python inference.py

  # Optional flags:
  #    python inference.py --model "meta-llama/Llama-3.1-8B-Instruct" --max_steps 60 --verbose
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
from typing import Any, Dict, List, Optional

import requests

sys.path.insert(0, os.path.dirname(__file__))

from src.envs.warehouse_env.client import WarehouseEnvClient
from src.envs.warehouse_env.models import Action, Observation

# ---------------------------------------------------------------------------
# CONFIGURATION
# ---------------------------------------------------------------------------

HF_TOKEN       = os.getenv("HF_TOKEN", "")
HF_ROUTER_URL  = "https://router.huggingface.co/v1/chat/completions"
DEFAULT_MODEL  = "meta-llama/Llama-3.1-70B-Instruct"   # change freely
ENV_BASE_URL   = os.getenv("ENV_URL", "http://localhost:8000")

SYSTEM_PROMPT = """You are an expert warehouse robot controller.
Your goal is to navigate a 12×12 warehouse grid, collect products in priority order
(HIGH first, then MEDIUM, then LOW), and deposit them at the loading dock (★).

RULES:
- Move: north / south / east / west / stay
- Pick up a product when adjacent (≤1 step away) using interact=pickup + target_sku
- Deposit at the loading dock using interact=deposit (you must BE on the dock)
- Recharge at ⚡ stations when battery < 25% using interact=recharge
- Shelves and collision zones are walls — you cannot enter them
- You can carry at most 3 items at once
- Battery depletes ~5% per move; carrying heavy items costs more

STRATEGY HINTS:
1. Always prioritise HIGH-priority SKUs first.
2. Plan a route: pick up 3 items, then head to dock, then repeat.
3. Recharge proactively — don't wait until battery is critical.
4. Use the Manhattan distance in the hint to find the nearest target.

RESPONSE FORMAT — output ONLY valid JSON, nothing else:
{
  "reasoning": "<1-2 sentence chain-of-thought explaining your decision>",
  "movement": "<north|south|east|west|stay>",
  "interact": "<pickup|deposit|recharge|none>",
  "target_sku": "<SKU string or null>"
}
"""


# ---------------------------------------------------------------------------
# PROMPT BUILDER
# ---------------------------------------------------------------------------

def build_user_prompt(obs: Observation, history: List[Dict[str, Any]]) -> str:
    """Convert an Observation into a rich natural-language prompt for the LLM."""

    uncollected = [p for p in obs.products if not p.collected and not p.deposited]
    uncollected_high   = [p for p in uncollected if p.priority == "high"]
    uncollected_medium = [p for p in uncollected if p.priority == "medium"]
    uncollected_low    = [p for p in uncollected if p.priority == "low"]

    products_lines = []
    for p in obs.products:
        status = "✅ DEPOSITED" if p.deposited else ("🎒 CARRYING" if p.collected else "📦 available")
        dist = abs(obs.agent_position[0] - p.position[0]) + abs(obs.agent_position[1] - p.position[1])
        products_lines.append(
            f"  {p.sku:8s} | {p.priority:6s} | pos={p.position} | dist={dist:2d} | value={p.value:.1f} | {status}"
        )

    visible_obstacles = [c for c in obs.visible_cells if c.kind in ("shelf_obstacle", "collision_zone")]
    visible_products  = [c for c in obs.visible_cells if c.kind == "product"]

    recent_history = history[-6:] if len(history) > 6 else history
    history_lines = []
    for h in recent_history:
        history_lines.append(
            f"  step {h['step']:3d} | action=({h['movement']},{h['interact']},{h['sku']}) | "
            f"reward={h['reward']:+.3f} | {h['msg']}"
        )

    return f"""=== WAREHOUSE STATE (Step {obs.steps_taken}/{obs.steps_taken + obs.steps_remaining}) ===

AGENT:
  Position    : {obs.agent_position}
  Battery     : {obs.battery_level:.0%}  {'⚠️ LOW!' if obs.battery_level < 0.25 else ''}
  Inventory   : {obs.inventory if obs.inventory else 'empty'} ({len(obs.inventory)}/{obs.carrying_capacity})
  Score       : {obs.score:.3f}

TASK PROGRESS:
  Deposited   : {obs.products_deposited}/{obs.total_products}
  Remaining   : {obs.products_remaining}  (High={len(uncollected_high)}, Medium={len(uncollected_medium)}, Low={len(uncollected_low)})

IMPORTANT LOCATIONS:
  Loading Dock     : {obs.loading_dock_position}
  Recharge Stations: {obs.recharge_stations}

ENVIRONMENT HINT (read carefully):
  {obs.hint}

PRODUCT MANIFEST:
{chr(10).join(products_lines)}

VISIBLE AREA (5×5 around agent):
  Obstacles in view : {[(c.position, c.kind) for c in visible_obstacles]}
  Products in view  : {[(c.position, c.sku) for c in visible_products]}

RECENT ACTION HISTORY:
{chr(10).join(history_lines) if history_lines else '  (no actions yet)'}

LAST ACTION RESULT: {obs.last_action_message}

Now output your JSON action. Remember: reasoning first, then fields.
"""


# ---------------------------------------------------------------------------
# LLM CALL
# ---------------------------------------------------------------------------

def call_llm(messages: List[Dict], model: str = DEFAULT_MODEL, max_tokens: int = 300) -> str:
    """Call Hugging Face Router API and return the raw completion string."""
    headers = {
        "Authorization": f"Bearer {HF_TOKEN}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": model,
        "messages": messages,
        "max_tokens": max_tokens,
        "temperature": 0.2,       # low temp = more deterministic reasoning
        "top_p": 0.9,
    }
    resp = requests.post(HF_ROUTER_URL, headers=headers, json=payload, timeout=60)
    resp.raise_for_status()
    return resp.json()["choices"][0]["message"]["content"]


def parse_llm_action(raw: str) -> Optional[Action]:
    """
    Extract the JSON block from the LLM response and parse it into an Action.
    Handles cases where the LLM wraps JSON in markdown code fences.
    """
    # Strip markdown fences if present
    cleaned = re.sub(r"```(?:json)?", "", raw).strip().strip("`")

    # Try to find JSON object in the response
    match = re.search(r"\{.*\}", cleaned, re.DOTALL)
    if not match:
        return None

    try:
        data = json.loads(match.group())
        return Action(
            movement=data.get("movement", "stay"),
            interact=data.get("interact", "none"),
            target_sku=data.get("target_sku") or None,
            metadata={"reasoning": data.get("reasoning", "")},
        )
    except Exception:
        return None


# ---------------------------------------------------------------------------
# MAIN INFERENCE LOOP
# ---------------------------------------------------------------------------

def run_episode(
    env: WarehouseEnvClient,
    model: str = DEFAULT_MODEL,
    max_steps: int = 80,
    verbose: bool = True,
) -> Dict[str, Any]:
    """
    Run one full episode using the LLM as the decision-making agent.

    Returns a summary dict with final score, steps, success flag.
    """
    print(f"\n{'='*70}")
    print(f"  🏭 WAREHOUSE RL — LLM EPISODE")
    print(f"  Model : {model}")
    print(f"  Max   : {max_steps} steps")
    print(f"{'='*70}\n")

    obs = env.reset()
    history: List[Dict[str, Any]] = []
    total_reward = 0.0

    for step_num in range(1, max_steps + 1):

        if obs.done:
            break

        # Build messages for LLM
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": build_user_prompt(obs, history)},
        ]

        # Call LLM
        try:
            raw_response = call_llm(messages, model=model)
        except requests.RequestException as e:
            print(f"  ⚠️  LLM API error: {e}. Using fallback (stay).")
            raw_response = '{"reasoning":"API error","movement":"stay","interact":"none","target_sku":null}'

        # Parse action
        action = parse_llm_action(raw_response)
        if action is None:
            print(f"  ⚠️  Could not parse LLM output. Defaulting to stay.")
            action = Action(movement="stay", interact="none")

        reasoning = action.metadata.get("reasoning", "")

        # Execute step
        obs = env.step(action)
        total_reward += obs.reward

        # Record history
        history.append({
            "step": step_num,
            "movement": action.movement,
            "interact": action.interact,
            "sku": action.target_sku,
            "reward": obs.reward,
            "msg": obs.last_action_message,
        })

        # Logging
        if verbose:
            batt_str = f"{obs.battery_level:.0%}"
            inv_str = ",".join(obs.inventory) if obs.inventory else "∅"
            reward_str = f"{obs.reward:+.3f}"
            valid_str = "✅" if obs.last_action_valid else "❌"
            print(
                f"  Step {step_num:3d} | {valid_str} | "
                f"{action.movement:5s} {action.interact:8s} {str(action.target_sku or ''):10s} | "
                f"r={reward_str} | batt={batt_str} | inv=[{inv_str}] | "
                f"dep={obs.products_deposited}/{obs.total_products}"
            )
            if reasoning:
                print(f"         💭 {reasoning[:100]}")
            if obs.hint and verbose:
                print(f"         📍 {obs.hint[:100]}")

        time.sleep(0.3)  # rate limiting

    # Episode summary
    print(f"\n{'='*70}")
    outcome = "✅ SUCCESS" if obs.is_success else "❌ FAILED"
    print(f"  {outcome}")
    print(f"  Score       : {obs.score:.3f}")
    print(f"  Steps taken : {obs.steps_taken}")
    print(f"  Deposited   : {obs.products_deposited}/{obs.total_products}")
    if obs.failure_reason:
        print(f"  Reason      : {obs.failure_reason}")
    print(f"{'='*70}\n")

    return {
        "success": obs.is_success,
        "score": obs.score,
        "steps": obs.steps_taken,
        "deposited": obs.products_deposited,
        "total_products": obs.total_products,
        "failure_reason": obs.failure_reason,
    }


# ---------------------------------------------------------------------------
# MULTI-EPISODE EVALUATION
# ---------------------------------------------------------------------------

def evaluate(
    env: WarehouseEnvClient,
    model: str = DEFAULT_MODEL,
    n_episodes: int = 3,
    max_steps: int = 80,
    verbose: bool = False,
) -> None:
    """Run multiple episodes and print aggregate statistics."""
    results = []
    for ep in range(1, n_episodes + 1):
        print(f"\n{'─'*70}")
        print(f"  EPISODE {ep}/{n_episodes}")
        result = run_episode(env, model=model, max_steps=max_steps, verbose=verbose)
        results.append(result)

    successes = sum(1 for r in results if r["success"])
    avg_score = sum(r["score"] for r in results) / len(results)
    avg_steps = sum(r["steps"] for r in results) / len(results)
    avg_dep   = sum(r["deposited"] for r in results) / len(results)

    print(f"\n{'='*70}")
    print("  📊 EVALUATION SUMMARY")
    print(f"  Episodes    : {n_episodes}")
    print(f"  Success rate: {successes}/{n_episodes} ({100*successes/n_episodes:.0f}%)")
    print(f"  Avg score   : {avg_score:.3f}")
    print(f"  Avg steps   : {avg_steps:.1f}")
    print(f"  Avg deposited: {avg_dep:.1f}/{results[0]['total_products']}")
    print(f"{'='*70}\n")


# ---------------------------------------------------------------------------
# CLI ENTRY POINT
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Warehouse RL — LLM Inference Loop")
    parser.add_argument("--model", default=DEFAULT_MODEL, help="HuggingFace model ID")
    parser.add_argument("--max_steps", type=int, default=80, help="Max steps per episode")
    parser.add_argument("--episodes", type=int, default=1, help="Number of episodes to run")
    parser.add_argument("--env_url", default=ENV_BASE_URL, help="Environment server URL")
    parser.add_argument("--verbose", action="store_true", default=True, help="Verbose step logging")
    parser.add_argument("--eval", action="store_true", help="Run multi-episode evaluation")
    args = parser.parse_args()

    if not HF_TOKEN:
        print("⚠️  HF_TOKEN environment variable not set.")
        print("    export HF_TOKEN=hf_...")
        print("    (Continuing — calls will fail without a valid token)\n")

    env = WarehouseEnvClient(base_url=args.env_url)

    # Verify server is up
    try:
        h = env.health()
        print(f"✅ Server connected: {h}")
    except Exception as e:
        print(f"❌ Cannot reach server at {args.env_url}: {e}")
        print("   Start it with: uvicorn src.envs.warehouse_env.server.app:app --port 8000")
        sys.exit(1)

    if args.eval or args.episodes > 1:
        evaluate(env, model=args.model, n_episodes=args.episodes,
                 max_steps=args.max_steps, verbose=args.verbose)
    else:
        run_episode(env, model=args.model, max_steps=args.max_steps, verbose=args.verbose)


if __name__ == "__main__":
    main()
